sylius_grid:
    grids:
        asdoria_admin_facet:
            driver:
                name: doctrine/orm
                options:
                    class: '%asdoria.model.facet.class%'
                    repository:
                        method: createQueryBuilderByFacetFilterId
                        arguments: [$facetFilterId]
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                title:
                    type: string
                    label: sylius.ui.name
                    sortable: translations.title
                facetType:
                    type: twig
                    label: asdoria.ui.facet_type
                    sortable: ~
                    options:
                        template: "@AsdoriaSyliusFacetFilterPlugin/Grid/Field/facetType.html.twig"
                facetGroup:
                    type: twig
                    label: asdoria.ui.facet_group
                    sortable: facetGroup
                    options:
                        template: "@AsdoriaSyliusFacetFilterPlugin/Grid/Field/facetGroup.html.twig"
                position:
                    type: twig
                    label: sylius.ui.position
                    sortable: position
                    path: .
                    options:
                        template: "@AsdoriaSyliusFacetFilterPlugin/Grid/Field/facet_position.html.twig"
            actions:
                main:
                    create:
                        type: links
                        label: asdoria.ui.manage_facet_create
                        icon: cubes
                        options:
                            links:
                                attribute:
                                    route: asdoria_admin_facet_create_product_attribute
                                    icon: plus
                                    label: asdoria.ui.new_facet_create_product_attribute
                                    parameters:
                                        facetFilterId: $facetFilterId
                                option:
                                    route: asdoria_admin_facet_create_product_option
                                    icon: plus
                                    label: asdoria.ui.new_facet_create_product_option
                                    parameters:
                                        facetFilterId: $facetFilterId
                                taxon:
                                    route: asdoria_admin_facet_create_taxon
                                    icon: plus
                                    label: asdoria.ui.new_facet_create_product_taxon
                                    parameters:
                                        facetFilterId: $facetFilterId
                    update_positions:
                        type: update_facet_positions
                item:
                    update:
                        type: update
                        options:
                            link:
                                route: asdoria_admin_facet_update
                                parameters:
                                    id: resource.id
                                    facetFilterId: $facetFilterId
                    delete:
                        type: delete
                        options:
                            link:
                                route: asdoria_admin_facet_delete
                                parameters:
                                    id: resource.id
                                    facetFilterId: $facetFilterId
